<!DOCTYPE html>
<html>
<head>
    <meta charset='UTF-8'>
    <title>Sign Up</title></head>
<body style="display: flex; justify-content: center; align-items: center; flex-direction: column; height: 98vh">
<h2>Sign Up</h2>
<form action='' method='POST'>
    <input type='text' name='login'><br>
    <input type='password' name='password'><br>
    <input type='submit' value='Sign Up'>
</form>
</body>
</html>